version: "3.8"

services:
  backend:
    image: backend-app
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:latest
    expose:
      - 6379
  frontend:
    image: frontend-app
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
